WIDTH = 500
HEIGHT = 50
GRAVITY = 1
JUMP_VEL = 2
GAME_TIME = 5

PROP_OFFSETL = 32
PROP_OFFSETR = WIDTH - 32

C_SIZE = [2, 8]
F_SIZE = [int(HEIGHT / 8), WIDTH]
LH_SIZE = [1, 12]
LV_SIZE = [6, 2]
LD_SIZE = [6, 7]
MG_SIZE = [1, 1]
B_SIZE = [1,1]

# Mando
M_LIVES = 3
M_HEALTH = 100
M_SIZE = [3, 2]
M_INIT_LOCATION = [HEIGHT - F_SIZE[0] - 1, int(PROP_OFFSETL / 2)]
