HEIGHT = 40
ENEMY_OFFSET = HEIGHT*2 + 10
WIDTH = 600 + ENEMY_OFFSET
GRAVITY = 1
JUMP_VEL = 2
GAME_TIME = 300

PROP_OFFSETL = 32
PROP_OFFSETR = WIDTH - ENEMY_OFFSET - 32

C_SIZE = [2, 8]
F_SIZE = [int(HEIGHT / 8), WIDTH]
LH_SIZE = [1, 12]
LV_SIZE = [6, 2]
LD_SIZE = [6, 7]
MG_SIZE = [1, 1]
B_SIZE = [1,1]
I_SIZE = [1,1]
P_SIZE = [1,2]

# Mando
M_LIVES = 3
M_HEALTH = 100
M_SIZE = [3, 2]
M_INIT_LOCATION = [HEIGHT - F_SIZE[0] - 1, int(PROP_OFFSETL / 2)]

E_LIVES = 5
E_HEALTH = 100
E_SIZE = [3,15]
E_INIT_LOCATION = [HEIGHT - F_SIZE[0] - 1, WIDTH - 30]